### PR TITLE
updated GamePanel.java

### PR DESCRIPTION
**Pull request by pr0ves**

### CODE REVIEW

**Comment by Derrreks** [comment]
I don't think the makeAJump() method will work because passing it a character only passes an instance of the character and so modifying c will not modify the actual character.

**Comment by pr0ves** [comment]
I knew that when a method has an object as an argument, as in `makeAJump(Character c)`, c is not an object in fact, but a pointer to an object that can't be modified for example using `c=new Character()`, but where you can use anyway the methods of the object to modify it.
Anyway i'll make some test and i'll let you know.

**Comment by Derrreks** [comment]
Sounds good.

**Comment by EthanSchoen** [comment]
This can no longer be merged, I will close this request in a day

**Pull request closed without merging**
